#samples one wants to joint call (alterantively one can specify projects)
samples:
    - /proj/ngi2016003/nobackup/NGI/ANALYSIS/P2652/piper_ngi/07_variant_calls/P2652_160.clean.dedup.recal.bam.genomic.vcf.gz
    - /proj/ngi2016003/nobackup/NGI/ANALYSIS/P2655/piper_ngi/07_variant_calls/P2655_234.clean.dedup.recal.bam.genomic.vcf.gz
    - /proj/ngi2016003/nobackup/NGI/ANALYSIS/P2655/piper_ngi/07_variant_calls/P2655_102.clean.dedup.recal.bam.genomic.vcf.gz 
    - /proj/ngi2016003/nobackup/NGI/ANALYSIS/P2652/piper_ngi/07_variant_calls/P2652_213.clean.dedup.recal.bam.genomic.vcf.gz
    - /proj/ngi2016003/nobackup/NGI/ANALYSIS/P2652/piper_ngi/07_variant_calls/P2652_239.clean.dedup.recal.bam.genomic.vcf.gz
    - /proj/ngi2016003/nobackup/NGI/ANALYSIS/P2652/piper_ngi/07_variant_calls/P2652_241.clean.dedup.recal.bam.genomic.vcf.gz
    - /proj/ngi2016003/nobackup/NGI/ANALYSIS/P2652/piper_ngi/07_variant_calls/P2652_244.clean.dedup.recal.bam.genomic.vcf.gz
#path to a folder containing an .interval file for each interval we want to work on
intervals: /proj/ngi2016003/nobackup/vezzi/SwedishReferenceGenomeProjects/develop/test/00_intervals
#True if one wants to use scratch
scratch: False
#True jobs will not be submitted 
dry_run: True
#size of the batches (for large projects 200)
batch_size: 4
#how the output file names should be called
output_header: "SRG"
#uppmax project where one need to seach for samples (used only if projects are specified)
uppmax_project: a201002
#options for walkers
#path to GATK
GATK : "/sw/apps/bioinfo/GATK/3.5.0/GenomeAnalysisTK.jar"
walkers:
    CombineGVCFs:
        - "-R /lupus/ngi/resources/piper/gatk_bundle/2.8/b37/human_g1k_v37.fasta" 
    GenotypeGVCFs:
        - "-R /lupus/ngi/resources/piper/gatk_bundle/2.8/b37/human_g1k_v37.fasta"
        - "-nt 16"
        - "--max_alternate_alleles 3"
        - "-D /lupus/ngi/resources//piper/gatk_bundle/2.8/b37/dbsnp_138.b37.vcf"  
    CatVariants:
        - "-R /lupus/ngi/resources/piper/gatk_bundle/2.8/b37/human_g1k_v37.fasta"
        - "-assumeSorted"
    SelectVariants:
        - "-R /lupus/ngi/resources/piper/gatk_bundle/2.8/b37/human_g1k_v37.fasta"
        - "-nt 16"
    VariantEval:
        - "-R /lupus/ngi/resources/piper/gatk_bundle/2.8/b37/human_g1k_v37.fasta"
        - "-comp:hapmap /lupus/ngi/resources/piper/gatk_bundle/2.8/b37/hapmap_3.3.b37.vcf"
        - "-D  /lupus/ngi/resources/piper/gatk_bundle/2.8/b37/dbsnp_138.b37.vcf"
    VariantRecalibrator:
        - "-R /lupus/ngi/resources/piper/gatk_bundle/2.8/b37/human_g1k_v37.fasta"
        - "-nt 16"
        - SNP:
             - "-resource:hapmap,known=false,training=true,truth=true,prior=15.0 /lupus/ngi/resources/piper/gatk_bundle/2.8/b37/hapmap_3.3.b37.vcf"
             - "-resource:omni,known=false,training=true,truth=true,prior=12.0 /lupus/ngi/resources/piper/gatk_bundle/2.8/b37/1000G_omni2.5.b37.vcf" 
             - "-resource:1000G,known=false,training=true,truth=false,prior=10.0 /lupus/ngi/resources/piper/gatk_bundle/2.8/b37/1000G_phase1.snps.high_confidence.b37.vcf"
             - "-resource:dbsnp,known=true,training=false,truth=false,prior=2.0 /lupus/ngi/resources/piper/gatk_bundle/2.8/b37/dbsnp_138.b37.vcf"
             - "-an QD"
             - "-an MQ"
             - "-an MQRankSum"
             - "-an ReadPosRankSum"
             - "-an FS"
             - "-an SOR"
             - "-an DP"
             - "-an InbreedingCoeff"
             - "-mode SNP"
             - "tranche 100.0 -tranche 99.9 -tranche 99.0 -tranche 90.0 "
        - INDEL:
              - "--maxGaussians 4"
              - "-resource:mills,known=false,training=true,truth=true,prior=12.0 /lupus/ngi/resources/piper/gatk_bundle/2.8/b37/Mills_and_1000G_gold_standard.indels.b37.vcf" 
              - "-resource:dbsnp,known=true,training=false,truth=false,prior=2.0 /lupus/ngi/resources/piper/gatk_bundle/2.8/b37/dbsnp_138.b37.vcf"
              - "-an QD"
              - "-an DP"
              - "-an FS"
              - "-an SOR" 
              - "-an ReadPosRankSum" 
              - "-an MQRankSum" 
              - "-an InbreedingCoeff"
              - "-mode INDEL"
              - "-tranche 100.0 -tranche 99.9 -tranche 99.0 -tranche 90.0"
    ApplyRecalibration:
        - "-R /lupus/ngi/resources/piper/gatk_bundle/2.8/b37/human_g1k_v37.fasta" 
        - "-nt 16"
        - SNP:
              - "--ts_filter_level 99.0"
              - "-mode SNP"
        - INDEL:
              - "--ts_filter_level 99.0"
              - "-mode INDEL" 


